version: '3.7'

x-es-logging:
  &es-logging
  options:
    max-size: '300m'
    max-file: '2'
  driver: json-file

x-standard-logging:
  &service-logging
  options:
    max-size: '500m'
    max-file: '3'
  driver: json-file

x-ui-logging:
  &ui-logging
  options:
    max-size: '100m'
    max-file: '3'
  driver: json-file

services:
  indyscan-indypool:
    container_name: indyscanpool
    image: ${INDYSCAN_INDYPOOL_IMAGE:-indypool:indyscanpool-v1.14.2}
    logging: *es-logging
    networks:
      - indyscan
    ports:
      - 9701-9708:9701-9708

  indyscan-elasticsearch:
    image: ${INDYSCAN_ELASTICSEARCH_IMAGE:-docker.elastic.co/elasticsearch/elasticsearch:7.6.1}
    container_name: indyscan-elasticsearch
    logging: *es-logging
    networks:
      - esnet
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - indyscan-es:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300

  indyscan-kibana:
    container_name: indyscan-kibana
    image: ${INDYSCAN_KIBANA_IMAGE:-docker.elastic.co/kibana/kibana:7.6.1}
    logging: *es-logging
    networks:
      - esnet
    environment:
      - ELASTICSEARCH_HOSTS=http://indyscan-elasticsearch.esnet:9200
    ports:
      - 5601:5601
    depends_on:
      - indyscan-elasticsearch
#
  indyscan-daemon:
    restart: unless-stopped
    image: ${INDYSCAN_DAEMON_IMAGE:-indyscan-daemon:4.0.0-dev}
    container_name: indyscan-daemon
    logging: *service-logging
    depends_on:
      - indyscan-elasticsearch
      - indyscan-indypool
    networks:
      - esnet
      - indyscan
    environment:
      - APP_CONFIGS=INDYSCANPOOL
      - LOG_LEVEL=info
      - LOG_HTTP_REQUESTS=true
      - LOG_HTTP_RESPONSES=true
      - SERVER_ENABLED=true
      - SERVER_PORT=3709
      - AUTOSTART=false
      - WORKER_TIMING=medium
    volumes:
      - ./app-configs-daemon/:/home/indyscan/indyscan-daemon/app-configs

  indyscan-api:
    restart: unless-stopped
    image: ${INDYSCAN_API_IMAGE:-indyscan-api:4.0.0-dev}
    container_name: indyscan-api
    logging: *service-logging
    environment:
      - ES_URL=http://indyscan-elasticsearch.esnet:9200
      - LOG_LEVEL=debug
      - PORT=3708
      - LOG_HTTP_REQUESTS=true
      - LOG_HTTP_RESPONSES=true
      - NETWORKS_CONFIG_PATH=${INDYSCAN_API_CONFIG_PATH:-/home/indyscan/indyscan-api/app-config-docker/localhost.json}
    networks:
      - indyscan
      - esnet
    ports:
      - 3708:3708
    volumes:
      - ./app-config-api/:/home/indyscan/indyscan-api/app-config-docker

  indyscan-webapp:
    restart: unless-stopped
    image: ${INDYSCAN_WEBAPP_IMAGE:-indyscan-webapp:4.0.0-dev}
    container_name: indyscan-webapp
    logging: *ui-logging
    environment:
      - INDYSCAN_API_URL=http://indyscan-api.indyscan:3708
      - PORT=3707
      - LOG_LEVEL=warn
      - LOG_HTTP_REQUESTS=false
      - LOG_HTTP_RESPONSES=false
    networks:
      - indyscan
    ports:
      - 3707:3707

  indyscan-daemon-ui:
    restart: unless-stopped
    image: ${INDYSCAN_DAEMON_UI_IMAGE:-indyscan-daemon-ui:4.0.0-dev}
    container_name: indyscan-daemon-ui
    logging: *ui-logging
    environment:
      - PORT=3710
      - PROXY_API_URL=http://indyscan-daemon.indyscan:3709
      - CHOKIDAR_USEPOLLING=true
    networks:
      - indyscan
    ports:
      - 3710:3710


networks:
  indyscan:
    name: indyscan
    driver: bridge
  esnet:
    name: esnet
    driver: bridge

volumes:
  indyscan-es:
    driver: local
